<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Populates fotos table with CDN URLs for LugarInteres images.
 */
class FotosCdnSeeder extends Seeder
{
    private const CDN_BASE = 'https://cdn.jsdelivr.net/gh/MariaSanchezFernandez/olivatour-v2@main/public/imagenes/lugaresInteres/imagenes';

    private const FOTOS_MAP = [
        'albanchezDeMagina_calderaDelTioLoboYElZurreon' => 10,
        'albanchezDeMagina_fuenteDelEspino' => 10,
        'alcalaLaReal_fortalezaDeLaMota' => 10,
        'alcalaLaReal_laAlcazaba' => 10,
        'alcalaLaReal_miradorDeSanMarcos' => 10,
        'alcalaLaReal_palacioAbacial' => 10,
        'alcaudete_fuenteDeLaVilla' => 10,
        'alcaudete_iglesiaDeSantaMariaLaMayor' => 10,
        'alcaudete_plazaDeAbastos' => 10,
        'aldeaquemadaYSantaElena_casaDelComandante' => 1,
        'aldeaquemadaYSantaElena_cascadaDeLaCimbarra' => 10,
        'aldeaquemadaYSantaElena_centroDeArteRupestre' => 10,
        'aldeaquemadaYSantaElena_estatuaDealfonsoViii' => 10,
        'aldeaquemadaYSantaElena_museoBatallaDeLasNavasDeTolosa1212' => 10,
        'andujar_miradorLosAlarcornes' => 5,
        'andujar_miradorMingorramos' => 10,
        'andujar_puenteRomano' => 10,
        'andujar_rutaDelToroBravo' => 9,
        'andujar_virgenDeLaCabeza' => 10,
        'arjonaYArjonilla_castilloDelTrovadorMacias' => 10,
        'arjonaYArjonilla_ermitaDeLaVirgenDeLaCabeza' => 10,
        'arjonaYArjonilla_iglesiaDeLaEncarnacion' => 10,
        'arjonaYArjonilla_iglesiaDeSanJuanBautista' => 10,
        'arjonilla_castiloDelTrovadorMacias' => 3,
        'arjonilla_ermitaDeLaVirgenDeLaCabeza' => 4,
        'arjonilla_iglesiaDeLaEncarnacion' => 10,
        'arroyoDelOjanco_centroDeInterpretacionDeLaCulturaRomana' => 10,
        'arroyoDelOjanco_iglesiaDeLaInmaculadaConcepcion' => 10,
        'arroyoDelOjanco_olivoDeFuentebuena' => 10,
        'baeza_catedralDeBaeza' => 10,
        'baeza_monumentoAntonioMachado' => 10,
        'baeza_plazaDelPopulo' => 10,
        'baeza_sanAndresYSantaMariaDelAlcazar' => 10,
        'bailen_burguillos' => 10,
        'bailen_museoDeLaBatallaDeBailen' => 10,
        'bailen_parqueDeEduardoCarvajal' => 10,
        'banosDeLaEncina_castilloDeBurgalimar' => 10,
        'banosDeLaEncina_ermitaDejesusDelLlano' => 10,
        'banosDeLaEncina_molinoDeVientoDelSantoCristo' => 10,
        'beasDeSegura_centroDeInterpretacionDeLaVillaDeBeas' => 10,
        'beasDeSegura_iglesiaYConventoDeLasCarmelitasDescalzas' => 10,
        'beasDeSegura_monasterioDeSanJoseDelSalvador' => 10,
        'beasDeSegura_murallasUrbanas' => 3,
        'bedmar_iglesiaParroquialDeLaAsuncion' => 10,
        'bedmar_rioCuadros' => 10,
        'benatae_fuenteDeLosCincoCanos' => 5,
        'benatae_iglesiaDeNuestraSenoraDeLaAsuncion' => 9,
        'benatae_miradorDePenalta' => 10,
        'benatae_senderoDeLaOsera' => 10,
        'cabraDelSantoCristo_encinaCentenariaDeCabraDeSantoCristo' => 10,
        'cabraDelSantoCristo_parroquiaDeNuestraSenoraDeLaExpectacion' => 10,
        'canena_balnearioDeCanena' => 10,
        'canena_castilloDeCanena' => 10,
        'canena_iglesiaDeNuestraSenoraDeLaConcepcion' => 10,
        'castellar_colegiataDeSantiagoApostol' => 10,
        'castellar_museoDeLaMemoriaHistoricaDeCastellar' => 10,
        'castellar_santuarioIberoCuevaDeLaLobera' => 10,
        'castilloDeLocubin_castilloDeLaVilleta' => 5,
        'castilloDeLocubin_iglesiaDeSanPedro' => 10,
        'castilloDeLocubin_puenteViejo' => 10,
        'cazorla_balconDeZabaleta' => 10,
        'cazorla_castilloDeLaYedra' => 10,
        'cazorla_fuenteDelOso' => 10,
        'cazorla_miradorDelChorro' => 10,
        'cazorla_nacelrio' => 10,
        'cazorla_picoPoyosDeLaMesa' => 10,
        'cazorla_rioCerezuelo' => 10,
        'cazorla_ruinasDeLaIglesiaDeSantaMariaDeGracia' => 10,
        'chiclanaDeSegura_ascensorPanoramico' => 10,
        'chiclanaDeSegura_ayuntamientoDeChiclanaDeSegura' => 10,
        'chiclanaDeSegura_miradorDeJorgeManrique' => 10,
        'chilluevarYPozoAlcon_badlandsDelGuadianaMenor' => 10,
        'chilluevarYPozoAlcon_bosquesCaducifoliosDeAltaMontana' => 10,
        'chilluevarYPozoAlcon_cascadoPuenteNevada' => 10,
        'chilluevarYPozoAlcon_cerradaLaBolera' => 10,
        'chilluevarYPozoAlcon_puenteViejoSobreElCanon' => 10,
        'chilluevar_igleisaDeNuestraSenoraDeLaPaz' => 8,
        'frailes_bodegasCampoameno' => 10,
        'frailes_parquePeriurbanoDeLosLlanos' => 10,
        'frailes_plazaDeLosToros' => 10,
        'fuensantaDeMartos_fuenteDeLaNegra' => 3,
        'fuensantaDeMartos_iglesiaParroquialDeNuestraSenoraDeLaFuensanta' => 10,
        'fuensantaDeMartos_paseoDelDespenadero' => 1,
        'fuensantaDeMartos_torreDelAlgarrobo' => 7,
        'fuerteDelRey_iglesiaDeLaNatividadDeNuestraSenora' => 7,
        'fuerteDelRey_molinoDelPrimerTercioDelSigloXx' => 10,
        'genave_castilloDeGenave' => 2,
        'genave_fuenteDeLaCamellona' => 10,
        'genave_iglesiaDeLaInmaculadaConcepcion' => 10,
        'genave_rutaDeLosMiradores' => 8,
        'higueraDeCalatrava_castilloDeHigueraDeCalatrava' => 6,
        'higueraDeCalatrava_iglesiaParroquialDeLaInmaculadaConcepcion' => 3,
        'hornos_castilloDeHornos' => 10,
        'hornos_iglesiaDeNuestraSenoraDeLaAsuncion' => 10,
        'hornos_miradorDelAguilon' => 10,
        'hornos_miradorLasCeladillas' => 10,
        'hornos_pantanoDelTranco' => 10,
        'huelma_castilloDeHuelma' => 10,
        'huelma_iglesiaDeLaInmaculadaConcepcion' => 10,
        'huelma_inicioSenderoPicoMagina' => 10,
        'huelma_miradorDeLosAlmendros' => 2,
        'iznatoraf_fuenteDelAlamillo' => 10,
        'iznatoraf_iglesiaDeLaAsuncion' => 10,
        'iznatoraf_murallasYTorreonDelReloj' => 10,
        'jaen_banosArabesYPalacioDeVillardompardo' => 10,
        'jaen_basilicaMenorDeSanIldefonso' => 10,
        'jaen_castilloDeSantaCatalina' => 10,
        'jaen_catedralDeLaAsuncion' => 10,
        'jaen_iglesiaDeSanJuan' => 10,
        'jaen_miradorDeLaCruz' => 10,
        'jamilena_ermitaDeSanFrancisco' => 5,
        'jamilena_iglesiaParroquialDeNuestraSenoraDeLaNatividad' => 10,
        'jimena_castilloDeJimena' => 10,
        'jimena_cuevaDeLaGraja' => 10,
        'jimena_pinarDeCanava' => 10,
        'jimena_santiagoElMayor' => 10,
        'jodar_castilloDeJodar' => 10,
        'jodar_colladoDelPortillo' => 10,
        'jodar_laSerrezuelaDeJodar' => 6,
        'laCarolinaYVilches_castilloDeVilches' => 10,
        'laCarolinaYVilches_iglesiaDeLaInmaculadaConcepcion' => 10,
        'laCarolinaYVilches_miradorPozoNuevoelCentenillo' => 10,
        'laCarolinaYVilches_parqueDeLaAquisgrana' => 10,
        'laCarolinaYVilches_paseomolinoDeViento' => 10,
        'laCarolina_iglesiaDeLaInmaculadaConcepcion' => 10,
        'laCarolina_miradorPozoNuevoelCentenillo' => 10,
        'laCarolina_parqueDeLaAquisgrana' => 10,
        'laCarolina_paseomolinoDeViento' => 10,
        'laGuardiaDeJaen_castilloDeLaGuardia' => 10,
        'laGuardiaDeJaen_cerroDeSanCristobal' => 10,
        'laGuardiaDeJaen_iglesiaDeNuestraSenoraDeLaAsuncion' => 10,
        'laGuardiaDeJaen_plazaIsabelIi' => 4,
        'laIruela_acebuchesDeLosVillaresDeBurunchelLaIruela' => 7,
        'laIruela_cascadaDeTobatobazoDeRechita' => 10,
        'laIruela_castilloDeLaIruela' => 10,
        'laIruela_ermitaDeLaVirgenDeLaCabeza' => 10,
        'laIruela_laMocha' => 10,
        'laIruela_olivoMilenario' => 10,
        'laPuertaDeSegura_castilloDeBujalame' => 10,
        'laPuertaDeSegura_iglesiaDeSanMateo' => 9,
        'laPuertaDeSegura_paseoDelRioGuadalimar' => 10,
        'linares_basilicaDeSantaMariaLaMayor' => 10,
        'linares_museoArqueologicoDeLinares' => 10,
        'linares_museoCapillaYCriptaDelHospitalDeLosMarquesesDeLinares' => 10,
        'linares_paseoDeLinarejos' => 10,
        'lopera_castilloDeLopera' => 10,
        'lopera_trincherasYBunkeresDeLaGuerraCivil' => 5,
        'losVillares_iglesiaDeSanJuanBautista' => 10,
        'losVillares_palacioDelVizconde' => 4,
        'losVillares_parquePeriurbanoDeLosVillares' => 10,
        'manchaReal_antiguoConventoDeLosCarmelitasDescalzos' => 10,
        'manchaReal_iglesiaParroquialDeSanJuanEvangelista' => 10,
        'manchaReal_miradorDeLaPuertaDeJaen' => 10,
        'manchaReal_torreDelRisquillo' => 10,
        'marmolejo_castilloDeLaAragonesa' => 10,
        'marmolejo_pantanillo' => 10,
        'marmolejo_puenteDeSanBartolome' => 10,
        'martos_castilloDeLaVilla' => 10,
        'martos_ermitaDeSanBartolome' => 10,
        'martos_iglesiaDeSanAmadorYSantaAna' => 10,
        'martos_parqueMunicipalManuelCarrasco' => 10,
        'martos_parroquiaDeSanFranciscoDeAsis' => 10,
        'martos_realIglesiaDeSantaMarta' => 10,
        'mengibar_casaPalacio' => 10,
        'mengibar_iglesiaDeSanPedroApostol' => 10,
        'mengibar_museoActivoTerraOleum' => 10,
        'mengibar_parroquiaDeLaInmaculadaConcepcion' => 10,
        'mengibar_torreDelHomenaje' => 10,
        'navasDeSanJuan_ayuntamientoDeNavasDeSanJuan' => 10,
        'navasDeSanJuan_ermitaVirgenDeLaEstrella' => 10,
        'navasDeSanJuan_miradorDeLosCalerines' => 10,
        'noalejo_ermitaDeLaVirgenDeBelen' => 8,
        'orcera_iglesiaDeNuestraSenoraDeLaAsuncion' => 10,
        'orcera_piscinaDeAmurjo' => 10,
        'orcera_torresDeSantaCatalina' => 2,
        'pealDeBecerro_castilloDeToya' => 10,
        'pealDeBecerro_centroDeInterpretacionYCamaraSepulcralDeToya' => 10,
        'pealDeBecerro_iglesiaDeNuestraSenoraDeLaEncarnacion' => 10,
        'porcuna_casaDeLaPiedra' => 10,
        'porcuna_museoArqueologicoDePorcuna' => 10,
        'porcuna_necropolisDinasticaDeCerrilloBlanco' => 10,
        'porcuna_parroquiaNuestraSenoraDeLaAsuncion' => 10,
        'porcuna_torreNuevaOTorreDeBoabdil' => 10,
        'porcuna_yacimientoIberoromanoDeObulco' => 1,
        'pozoAlcon_embalseDeLaBolera' => 10,
        'pozoAlcon_iglesiaDeNuestraSenoraDeLaEncarnacionDePozoAlcon' => 10,
        'pozoAlcon_miradorGuazalamanco' => 10,
        'puenteDeGenave_iglesiaDeSanIsidroLabrador' => 2,
        'puenteDeGenave_puenteRomano' => 6,
        'puenteDeGenave_torresDePenolite' => 8,
        'quesada_arcoDeLaManquitaDeUtrera' => 2,
        'quesada_calleAdentro' => 4,
        'quesada_museoZabaletaMiguelHernandez' => 10,
        'rusYCanena_castilloDeCanena' => 10,
        'rus_iglesiaDeNuestraSenoraDeLaAsuncion' => 10,
        'rus_molinoDeVientoDeRus' => 10,
        'rus_plazaDelAyuntamientoYEntornoHistorico' => 10,
        'sabiote_barrioDelAlbaicinDeSabiote' => 10,
        'sabiote_castilloDeSabiote' => 10,
        'sabiote_parajeNaturalLaCorregidora' => 10,
        'sabiote_plazaAlonsoDeVandelvira' => 10,
        'santaElena_estatuaDealfonsoViii' => 10,
        'santaElena_museoBatallaDeLasNavasDeTolosa1212' => 10,
        'santiagoDeCalatrava_camaraAgraria' => 7,
        'santiagoDeCalatrava_parroquiaDeLaVirgenDeLaEstrella' => 6,
        'santiagoDeCalatrava_plazaDeLaIglesia' => 6,
        'santiagopontones_centroDeVisitantesTorreDelVinagre' => 10,
        'santiagopontones_iglesiaParroquialDeSantiagoApostol' => 10,
        'santiagopontones_nacimientoDelRioSegura' => 10,
        'santistebanDelPuerto_huellasDeDinosaurio' => 10,
        'santistebanDelPuerto_miradorDeMontaraz' => 1,
        'santistebanDelPuerto_santuarioDeSantaMariaDelCollado' => 10,
        'seguraDeLaSierra_banosArabes' => 10,
        'seguraDeLaSierra_castilloDeSeguraDeLaSierra' => 10,
        'seguraDeLaSierra_fuenteImperialDeCarlosV' => 10,
        'seguraDeLaSierra_miradorDePenalta' => 10,
        'siles_arcoDeLaMalena' => 2,
        'siles_arcoDeSanGregorio' => 10,
        'siles_areaRecreativaPenaDelOlivar' => 10,
        'siles_ermitaDeSanRoque' => 10,
        'siles_torreDelCubo' => 10,
        'sorihuelaDelGuadalimar_fuenteDeLaPlazaDeEspana' => 6,
        'sorihuelaDelGuadalimar_iglesiaParroquialDeSantaAgueda' => 10,
        'sorihuelaDelGuadalimar_torreDelHomenajeDelCastilloDeSorihuela' => 10,
        'torredelcampo_castilloDelBerrueco' => 10,
        'torredelcampo_cerroMiguelico' => 10,
        'torredelcampo_iglesiaParroquialDeSanBartolome' => 10,
        'torredonjimeno_castilloDeTorredonjimeno' => 10,
        'torredonjimeno_iglesiaDeSanPedro' => 10,
        'torredonjimeno_iglesiaDeSantaMaria' => 10,
        'torredonjimeno_museoDelAceiteYOlivar' => 10,
        'torreperogil_cortijoDeMainilla' => 7,
        'torresDeAlbanchez_castilloDeLaYedra' => 10,
        'torresDeAlbanchez_iglesiaDeNuestraSenoraDeLaPresentacion' => 10,
        'torresDeAlbanchez_rutaDeSenderismoAlCastillo' => 10,
        'torresDeAlbanchez_torreDelHomenaje' => 10,
        'torres_iglesiaParroquialDeSantoDomingoDeGuzman' => 10,
        'torres_palacioDeLosMarquesesDeCamarasa' => 5,
        'ubeda_ayuntamientoDeUbeda' => 10,
        'ubeda_elSalvador' => 10,
        'ubeda_hospitalDeSantiago' => 10,
        'ubeda_miradoresDelAlcazar' => 10,
        'ubeda_palacioVelaDeLosCobos' => 10,
        'ubeda_sanLorenzo' => 6,
        'ubeda_sanPablo' => 10,
        'ubeda_santaMaria' => 10,
        'valdepenasDeJaen_iglesiaDeSantiagoApostol' => 10,
        'valdepenasDeJaen_laPandera' => 10,
        'valdepenasDeJaen_museoMolinoDeSantaAna' => 10,
        'vilanuevaDelArzobispo_caballoTorraso' => 10,
        'vilanuevaDelArzobispo_charcoDelAceite' => 10,
        'vilanuevaDelArzobispo_miradorTapadero' => 10,
        'vilanuevaDelArzobispo_piscinaNaturalDeMogon' => 10,
        'vilches_castilloDeVilches' => 10,
        'vilches_iglesiaDeSanMiguelArcangel' => 10,
        'vilches_presaDeLaFernandina' => 10,
        'villacarrillo_areaRecreativaDeLaCuevaDelPeinero' => 10,
        'villacarrillo_cascadaDeLaOsera' => 10,
        'villacarrillo_cortijoLosGuerreros' => 4,
        'villacarrillo_elAguardentero' => 10,
        'villacarrillo_iglesiaDeNuestraSenoraDeLaAsuncion' => 10,
        'villardompardo_castilloDeVillardompardo' => 10,
        'villardompardo_iglesiaDeNuestraSenoraDeGracia' => 6,
        'villardompardo_parajeDelCalvario' => 10,
        'villatorres_ciudadIberoromanaDeIliturgi' => 5,
        'villatorres_ermitaDelSantoCristoDeLaSalud' => 6,
        'villatorres_iglesiaDeNuestraSenoraDeLaAsuncion' => 10,
    ];

    public function run(): void
    {
        $existing = DB::table('fotos')
            ->where('fotoable_type', 'App\\Models\\LugarInteres')
            ->count();
        if ($existing > 0) { return; }

        foreach (self::FOTOS_MAP as $key => $count) {
            $pos = strpos($key, '_');
            if ($pos === false) continue;
            $pobNorm   = substr($key, 0, $pos);
            $lugarNorm = substr($key, $pos + 1);

            $lugar = DB::table('lugares_interes')
                ->join('poblaciones', 'lugares_interes.poblacion_id', '=', 'poblaciones.id')
                ->where('lugares_interes.nombreNormalizado', $lugarNorm)
                ->where('poblaciones.nombreNormalizado', $pobNorm)
                ->select('lugares_interes.id')
                ->first();

            if (!$lugar) continue;

            $rows = [];
            $now = now();
            for ($i = 0; $i < $count; $i++) {
                $rows[] = [
                    'url'           => self::CDN_BASE . '/' . $key . '_' . $i . '.jpg',
                    'fotoable_type' => 'App\\Models\\LugarInteres',
                    'fotoable_id'   => $lugar->id,
                    'created_at'    => $now,
                    'updated_at'    => $now,
                ];
            }
            if (!empty($rows)) { DB::table('fotos')->insert($rows); }
        }
    }
}
